zdtm: workaround ip route dump problem
This is needed to workaround the problem with "ip route save":
(00.113153)     Running ip route save
Error: ipv4: FIB table does not exist.

https://github.com/checkpoint-restore/criu/issues/747
https://jira.sw.ru/browse/PSBM-120728

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>