pstree: Make lookup_create_pid() able to create tasks with pid->level > 1
Pid may contain more then one level, so this patch teaches the function
to work with such pids. The signify difference after this patch is that
we link a new item in several rb_root in every ns.

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>

+++
pstree: use RB_EMPTY_NODE to check that node is not linked

When new rb_root is created for pidns it is initialized with
RB_ROOT, so ns->pid.rb_root.rb_node is NULL at first. Later
then insert first node in lookup_create_pid() to these rb-tree
it will have (NULL & color) in node->rb_parent_color.

So the check "!rb_parent(&found->ns[i].node)" will be true for
the rb-tree's root node, and criu will fail lookup these node.

We haven't hit that yet as to get to these check we need task in
at least two levels of pidns which at the same time is the root
in rb-tree on e.g. level 0.

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Reviewed-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Signed-off-by: Andrei Vagin <avagin@virtuozzo.com>

+++
pstree: Do not populate zero levels of task's pid

If task's pid were hashed before the task itself
(this may happen, when another task has sid or pgid
equal to this pid), the pid mustn't contain zero
levels. So, if pgid or sid has zero levels, we should
not add them.

Otherwise, session04 --iter 3 fails with:

=[log]=> dump/zdtm/static/session04/30/2/restore.log
------------------------ grep Error ------------------------
(01.858187)      6: Restoring children in our session:
(01.858206)      6: Forking task with 303 pid (flags 0x600)
(01.869893)      1: PID: real 145 virt 15
(01.870247)      1: Forking task with 20 pid (flags 0x0)
(01.872948) Error (criu/cr-restore.c:381): 0: Write -1 to sys/kernel/ns_last_pid: Invalid argument
(01.873030) Error (criu/namespaces.c:2664): Can't set next pid
(01.873103)      1: Error (criu/ns-common.c:46): Error answer
(01.873123)      1: Error (criu/cr-restore.c:404): Can't request next pid
(01.873135)      1: Error (criu/cr-restore.c:1321): Can't set next pid
(01.873310)      1: Error (criu/cr-restore.c:1434): Can't fork for 20: No such file or directory

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Acked-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Signed-off-by: Andrei Vagin <avagin@virtuozzo.com>

rebase: merge fixes

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

Feature: Pid & User namespaces