zdtm: fix unchecked snprintf truncation in bridge_port_settings
bridge_port_settings.c: In function ‘main’:
bridge_port_settings.c:57:11: error: ‘%s’ directive output may be
truncated writing up to 255 bytes into a region of size 106
[-Werror=format-truncation=]
  EXEC_CMD("bridge -d link show > %s", file1);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~

https://ci.openvz.org/job/CRIU/job/CRIU-virtuozzo8/job/vz7-u16/176/console

Fixes: bebbded98 ("zdtm: add bridge and fdb tests")
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>