compel: silence std_sprintf returned string size check
Before that we had:

In file included from criu/pie/restorer.c:57:
criu/pie/../ns-common.c: In function ‘pid_ns_helper_socket_name’:
criu/pie/../ns-common.c:16:9: error: ‘std_sprintf’ accessing 256 bytes
in a region of size 108 [-Werror=stringop-overflow=]
   16 |         std_sprintf(addr->sun_path, "%s%d", prefix, id);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Because when we use std_sprintf from ns-common.c we have destination
with a smaller size than char[STD_LOG_SIMPLE_CHUNK].

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>