zdtm: fix compilation from vzt-cpt
An inline function must be either static or defined in another translation
unit, otherwise linker might be confused

14.08.2020-12.21.01:  LINK      bind-mount-unix-multi
14.08.2020-12.21.01: bind-mount-unix-multi.o: In function `main':
14.08.2020-12.21.01: /vz/tmp/criutestsXlN3RV/test/zdtm/static/bind-mount-unix-multi.c:163: undefined reference to `forkwrite'
14.08.2020-12.21.01: collect2: error: ld returned 1 exit status
14.08.2020-12.21.01: make: *** [../Makefile.inc:68: bind-mount-unix-multi] Error 1

Fixes: b572b937c25 ("zdtm: add testcase for multiple unix sk bindmounts")

https://jira.sw.ru/browse/PSBM-106860

Reviewed-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Signed-off-by: Andrey Zhadchenko <andrey.zhadchenko@virtuozzo.com>